export enum DashboardState {
  CONTEXT_REQUIRED = "CONTEXT_REQUIRED",
  SCANNING = "SCANNING",
  NO_THREADS = "NO_THREADS",
  THREADS_RISKY_ONLY = "THREADS_RISKY_ONLY",
  THREADS_AVAILABLE = "THREADS_AVAILABLE",
}
